services:
  svc-3070:
    container_name: 'svc-3070'
    build: .
    image: seed-vc:latest
    environment:
      - LC_ALL=C.UTF-8
    volumes:
      - type: volume
        source: TTD-Data
        target: /app/checkpoints
        volume:
          nocopy: true
          subpath: seed-vc/checkpoints
      - type: volume
        source: TTD-Data
        target: /root/.cache
        volume:
          nocopy: true
          subpath: seed-vc/cache
    working_dir: /app
    shm_size: 16G
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "7001:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]
  svc-p5000:
    container_name: 'svc-p5000'
    extends: svc-3070
    ports: !override
      - "7002:7860"
    deploy: !override
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "1" ]
              capabilities: [ gpu ]

volumes:
  TTD-Data:
    external: true
