services:
  svc-api:
    container_name: 'svc'
    build: .
    image: seed-vc:latest
    environment:
      - LC_ALL=C.UTF-8
    volumes:
      - /data/ttd/:/data/ttd
      - /data/ttd/seed-vc/.cache/:/root/.cache
    working_dir: /app
    shm_size: 16G
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "7000:7866"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]