services:
  svc-api-1:
    container_name: 'svc-api-1'
    build: .
    image: seed-vc:latest
    environment:
      - LC_ALL=C.UTF-8
    volumes:
      - /data/ttd/:/data/ttd
      - /data/ttd/seed-vc/checkpoints/:/app/checkpoints
      - /data/ttd/seed-vc/.cache/:/root/.cache
    working_dir: /app
    shm_size: 16G
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "7000:7856"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]
  svc-api-2:
    container_name: 'svc-api-2'
    extends: svc-api-1
    ports: !override
      - "7001:7856"
    deploy: !override
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["1"]
            capabilities: [gpu]
  svc-api-3:
    container_name: 'svc-api-3'
    extends: svc-api-1
    ports: !override
      - "7002:7856"
    deploy: !override
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["2"]
            capabilities: [gpu]